#!/usr/bin/env python3
"""
InflationGuard - invariant synthesizer.

The detector finds *where* the donatable-price / rounding-inflation pattern
lives. This synthesizer turns each flagged share-vault into an executable
Foundry **invariant suite** that encodes the formal negation of the bug class -
the property the protocol must hold and that a happy-path test never checks.

It is the "auto-generated test" half of the tool (mirroring Olympix's
auto-test-generation philosophy): a developer runs the detector, gets a finding,
and the synthesizer hands back a property test that (a) PASSES on correct code,
(b) FAILS on the historic-bug version, and (c) is later used by the mutation gate
to prove the protection is actually exercised.

The three synthesized properties (the negation of P1/P2/P3):
    INV-1 donationCannotMovePrice  - a bare token transfer must not move price/share
    INV-2 noZeroShareDeposit       - a non-zero deposit must mint non-zero shares
    INV-3 noFreeLunch              - no actor redeems more value than they contributed

Usage:
    python3 tool/inflationguard/synthesize_invariant.py \
        --safe SafeVault --safe-import ../../src/safe/SafeVault.sol \
        --vuln VulnerableVault --vuln-import ../../src/vulnerable/VulnerableVault.sol \
        --asset crvUSD --out test/generated/InflationGuardVaultInvariant.t.sol
"""
import argparse
import os

TEMPLATE = r'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// =============================================================================
//  GENERATED BY InflationGuard  -  do not edit by hand.
//  Source: tool/inflationguard/synthesize_invariant.py
//  Target spec: {{ kind: "share-vault", deposit: "deposit(uint256)",
//                 redeem: "redeem(uint256)", price: "convertToAssets(uint256)" }}
//
//  When InflationGuard's static pass flags a donatable-price share vault, it
//  emits this stateful invariant suite. The three properties below are the
//  formal negation of the share-VAULT inflation sub-class (the lending-pair /
//  exchange-rate face, e.g. Resupply, is covered by a separate template): if any
//  can be violated by a sequence of deposits / redeems / DONATIONS, it inflates.
//
//  Run against the shipping contract:   forge test --mc {CONTRACT}
//  Prove it catches the historic bug:   GUARD_TARGET=vulnerable forge test --mc {CONTRACT}
// =============================================================================

import {{Test}} from "forge-std/Test.sol";
import {{MockERC20}} from "../../src/mocks/MockERC20.sol";
import {{IShareVault}} from "../../src/interfaces/IShareVault.sol";
import {{{VULN}}} from "{VULN_IMPORT}";
import {{{SAFE}}} from "{SAFE_IMPORT}";

/// @dev Drives the vault with the three operations that matter for inflation:
///      legitimate deposit, legitimate redeem, and a bare token DONATION - the
///      operation happy-path tests never perform, which is exactly why they
///      miss this bug.
contract VaultHandler is Test {{
    IShareVault public immutable vault;
    MockERC20 public immutable asset;
    address[] public actors;

    // Ghost state - the witnesses an invariant violation leaves behind.
    bool public sawZeroShareDeposit; // a >0 deposit that minted 0 shares
    bool public donationMovedPrice; // a bare donation that changed price/share
    mapping(address => uint256) public putIn; // assets contributed (deposit + donation)
    mapping(address => uint256) public tookOut; // assets redeemed

    constructor(IShareVault _vault, MockERC20 _asset, address[] memory _actors) {{
        vault = _vault;
        asset = _asset;
        actors = _actors;
    }}

    function numActors() external view returns (uint256) {{
        return actors.length;
    }}

    function actorAt(uint256 i) external view returns (address) {{
        return actors[i];
    }}

    function _actor(uint256 seed) internal view returns (address) {{
        return actors[seed % actors.length];
    }}

    function deposit(uint256 seed, uint256 assets) external {{
        address a = _actor(seed);
        assets = bound(assets, 0, 1e24);
        asset.mint(a, assets);
        vm.startPrank(a);
        asset.approve(address(vault), type(uint256).max);
        uint256 shares = vault.deposit(assets);
        vm.stopPrank();
        if (assets > 0 && shares == 0) sawZeroShareDeposit = true;
        putIn[a] += assets;
    }}

    function donate(uint256 seed, uint256 amount) external {{
        address a = _actor(seed);
        amount = bound(amount, 1, 1e24);
        uint256 ppsBefore = vault.convertToAssets(1e18);
        asset.mint(a, amount);
        vm.prank(a);
        asset.transfer(address(vault), amount); // <-- the donation
        uint256 ppsAfter = vault.convertToAssets(1e18);
        if (ppsAfter != ppsBefore) donationMovedPrice = true;
        putIn[a] += amount;
    }}

    function redeem(uint256 seed, uint256 shares) external {{
        address a = _actor(seed);
        uint256 bal = vault.balanceOf(a);
        if (bal == 0) return;
        shares = bound(shares, 0, bal);
        vm.prank(a);
        uint256 assets = vault.redeem(shares);
        tookOut[a] += assets;
    }}
}}

contract {CONTRACT} is Test {{
    MockERC20 internal asset;
    IShareVault internal vault;
    VaultHandler internal handler;

    function setUp() public {{
        asset = new MockERC20("{ASSET_NAME}", "{ASSET}", 18);

        // GUARD_TARGET=vulnerable points the SAME spec at the historic buggy
        // contract, demonstrating the synthesized invariant would have caught it.
        string memory target = vm.envOr("GUARD_TARGET", string("safe"));
        if (keccak256(bytes(target)) == keccak256(bytes("vulnerable"))) {{
            vault = IShareVault(address(new {VULN}(asset)));
        }} else {{
            vault = IShareVault(address(new {SAFE}(asset)));
        }}

        address[] memory actors = new address[]({NACTORS});
{ACTOR_LINES}

        handler = new VaultHandler(vault, asset, actors);
        targetContract(address(handler));
    }}

    /// INV-1 (kills P1): a bare donation must never move the price per share.
    function invariant_donationCannotMovePrice() public view {{
        assertFalse(handler.donationMovedPrice(), "price/share moved by a bare token donation");
    }}

    /// INV-2 (kills P2/P3): a non-zero deposit must mint non-zero shares.
    function invariant_noZeroShareDeposit() public view {{
        assertFalse(handler.sawZeroShareDeposit(), "a non-zero deposit minted zero shares");
    }}

    /// INV-3 (conservation): with no yield, no actor can redeem more than they
    /// contributed. This is the economic "no free lunch" property.
    ///
    /// DUST tolerates benign floor-division rounding from the virtual-shares
    /// offset (a few wei across a run). It is ~1e9, while a successful inflation
    /// attack redistributes >=1e18 (a victim's whole deposit) - nine-plus orders
    /// of magnitude apart, so the threshold can never mask a real theft.
    uint256 internal constant DUST = 1e9;

    function invariant_noFreeLunch() public view {{
        uint256 n = handler.numActors();
        for (uint256 i = 0; i < n; i++) {{
            address a = handler.actorAt(i);
            assertLe(handler.tookOut(a), handler.putIn(a) + DUST, "actor extracted more than contributed");
        }}
    }}
}}
'''


def main():
    ap = argparse.ArgumentParser(description="Synthesize an InflationGuard invariant suite.")
    ap.add_argument("--safe", default="SafeVault")
    ap.add_argument("--safe-import", default="../../src/safe/SafeVault.sol")
    ap.add_argument("--vuln", default="VulnerableVault")
    ap.add_argument("--vuln-import", default="../../src/vulnerable/VulnerableVault.sol")
    ap.add_argument("--asset", default="crvUSD")
    ap.add_argument("--asset-name", default="Curve USD")
    ap.add_argument("--contract", default="InflationGuardVaultInvariant")
    ap.add_argument("--actors", default="alice,bob,eve")
    ap.add_argument("--out", default="test/generated/InflationGuardVaultInvariant.t.sol")
    ap.add_argument(
        "--from-finding",
        help="path to a JSON findings file from inflationguard_slither.py --json; "
        "the flagged donatable-price/no-virtual-shares contract becomes the GUARD_TARGET=vulnerable target",
    )
    a = ap.parse_args()

    # Detect -> Synthesize wiring: consume the detector's machine-readable finding
    # so the vulnerable target is chosen by the static pass, not hardcoded.
    if a.from_finding:
        import json
        findings = json.load(open(a.from_finding))
        keyed = [f for f in findings if f.get("rule") in ("donatable-price-source", "no-virtual-shares-offset")]
        if not keyed:
            raise SystemExit("--from-finding: no donatable-price/no-virtual-shares finding to synthesize from")
        fnd = keyed[0]
        a.vuln = fnd["contract"]
        if fnd.get("file"):
            # detector emits a project-relative path like src/vulnerable/VulnerableVault.sol
            a.vuln_import = "../../" + fnd["file"].lstrip("./")
        print(f"InflationGuard: synthesizing from finding -> {fnd['rule']} in {a.vuln} ({fnd.get('file','?')})")

    actors = [x.strip() for x in a.actors.split(",") if x.strip()]
    actor_lines = "\n".join(
        f'        actors[{i}] = makeAddr("{name}");' for i, name in enumerate(actors)
    )

    out = TEMPLATE.format(
        CONTRACT=a.contract,
        SAFE=a.safe, SAFE_IMPORT=a.safe_import,
        VULN=a.vuln, VULN_IMPORT=a.vuln_import,
        ASSET=a.asset, ASSET_NAME=a.asset_name,
        NACTORS=len(actors), ACTOR_LINES=actor_lines,
    )

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(out)
    print(f"InflationGuard: synthesized {len(out.splitlines())}-line invariant suite -> {a.out}")
    print(f"  properties: donationCannotMovePrice, noZeroShareDeposit, noFreeLunch")
    print(f"  verify clean:   forge test --mc {a.contract}")
    print(f"  verify catches: GUARD_TARGET=vulnerable forge test --mc {a.contract}")


if __name__ == "__main__":
    main()
